services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: geo-postgres
    environment:
      POSTGRES_DB: geospatial
      POSTGRES_USER: geouser
      POSTGRES_PASSWORD: geopass123
    ports:
      - "5435:5432"
    volumes:
      - geo_pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geouser -d geospatial"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: geo-redis
    ports:
      - "6381:6379"
    volumes:
      - geo_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  geo_pgdata:
  geo_redisdata:
